# Generated by Django 5.2.16 on 2026-07-24 19:29

from django.db import migrations, models
import mailqueue.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0007_auto_20200318_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=mailqueue.utils.get_storage,
                                   upload_to=mailqueue.utils.upload_to),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='bcc_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='cc_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='from_address',
            field=models.CharField(db_index=True, max_length=250, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='reply_to',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reply to'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='sent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=250, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='to_address',
            field=models.CharField(db_index=True, max_length=250, verbose_name='To'),
        ),
    ]
